### ISSUE TITLE
Overlapping Elements in Unit Frames

### ISSUE THREAD

**Issue by luitzifa** [NoobTaco/NoobTacoUI#25]
I newly installed this and these Bugs really bother me:

Player UnitFrame:
Aurabar overlaps Buffs

Target UnitFrame:
Buffs and Debuffs overlapping

**Comment by NoobTaco** [comment]
Hello @luitzifa Could you let me know what resolution you are using?

**Comment by luitzifa** [comment]
Hi @NoobTaco ,
my resolution is 3440x1440.
Here is a screenshot, to show the Problem.
![WoWScrnShot_052721_145723](https://user-images.githubusercontent.com/8862016/119830427-89ed5300-befc-11eb-9450-d5f8564841fe.jpg)

**Comment by NoobTaco** [comment]
Thank you @luitzifa I will look into it with an upcoming pass and see what I can do to clean that up.

**Comment by denverpunks** [comment]
This issue can easily be fixed by toggling the anchor point and moving them out..
That's what I have been doing anyway. I Hope that helps..

![111](https://user-images.githubusercontent.com/85754916/121713252-4705b080-caa2-11eb-928b-6b3228668e61.png)

**Comment by Smexhy** [comment]
Hey, I think this is kind of the same topic so I will add it here. I too have 4k resolution for my UI and game window (rendering is set to normal 1920x1080 but that's unrelated to the UI).

I am having these fonts overlaping and sometimes standing out of the panel entirely as you can see on the pictures. Would you be perhaps able to fix this? Really like your UI! Transitioned from Benik to this and the space on bars and clean design pleases me.

![CleanShot 2021-08-14 at 15 05 52@2x](https://user-images.githubusercontent.com/4880625/129447348-148e8127-02e2-4a47-9377-8ff7de1f6b50.png)

![CleanShot 2021-08-14 at 15 06 47@2x](https://user-images.githubusercontent.com/4880625/129447357-4c9d298e-c7fc-4420-b1d4-ab244d9e2447.png)

**Comment by NoobTaco** [comment]
The initial bug report should be resolved in 1.3.0
