### ISSUE TITLE
WoW Classic TBC - Bank bags not showing

### ISSUE THREAD

**Issue by Onfire93** [NoobTaco/NoobTacoUI#26]
Hey, when opening bank bags its not showing. My characters bags is opening, but bank's no. 

After setup, you can reset anchors then will show bank spaces.

**Comment by NoobTaco** [comment]
Hi there @Onfire93,  

What resolution are you using for your system? This might be causing the anchor to be off screen.

**Comment by Onfire93** [comment]
1920x1080

**Comment by NoobTaco** [comment]
Sounds like the smaller rez is and ElvUI's setup could be placing it slightly off. 

Since there is a work around, I will get a note into the readme about it.

Thanks for the report.
