### ISSUE TITLE
missing level numbers on guild window

### ISSUE THREAD

**Issue by xmcdizzle** [NoobTaco/NoobTacoUI#27]
Good afternoon, 

Recently I came across something unusual and not sure why it would have happened, but if you have Noobtaco installed, if you go to your guild window and look at the levels of characters, every number is listed for which level they are, except lvl 60. 

If a character is lvl 60, it just shows a ... 

Here is a screenshot of it I took a day or so ago

![](https://cdn.discordapp.com/attachments/807076564935376946/846602361626689546/unknown.png)

**Comment by NoobTaco** [comment]
Hello @xmcdizzle This could be from another addon or screen res. I will keep looking into being able to replicate but so far, I do not see the same issue.

Can you give me more information about other addons you might be running that could be conflicting?

Thanks

![image](https://user-images.githubusercontent.com/1172935/120222151-58260600-c1f4-11eb-86da-84c5ed3adedd.png)

**Comment by xmcdizzle** [comment]
Super weird. I don’t think I have any other addons that affect it. Most notable ones are 

Attune
DBM
PAWN
GatherMate2
Baggon
Auctioner

I will send the full list when I get back to my PC, but it used to work perfectly up until an update of some sort.

**Comment by xmcdizzle** [comment]
Mike, here is the list of addons I am using all together on top of ElvUI/NoobTaco
AtlasLootClassic
Attune
AuctionatorBagonDecursiveDejamarkDismounterDominosGatherMate2ItemRackLeatrix MapsMik's SBTPawnPortal MageRCLootCouncilRecountThreatClassicWeakaurasCharacterStatsTBCDBM
Any of these you think could cause that issue with the lvl not showing for 60? I will try turning off each addon 1 at a time to see which one it could be. 
    On Monday, May 31, 2021, 02:50:04 PM EDT, Zack Gall ***@***.***> wrote:  
 
 Super weird. I don’t think I have any other addons that affect it. Most notable ones are 
AttuneDBMPAWNGatherMate2BaggonAuctioner
I will send the full list when I get back to my PC, but it used to work perfectly up until an update of some sort. 
Sent from my iPhone

On May 31, 2021, at 12:42 PM, Mike Norton ***@***.***> wrote:



﻿


Hello @xmcdizzle This could be from another addon or screen res. I will keep looking into being able to replicate but so far, I do not see the same issue.

Can you give me more information about other addons you might be running that could be conflicting?

Thanks

**Comment by xmcdizzle** [comment]
So the first Addon I disabled just to see, was NoobTacoUI. The level 60 now shows. I am going to reinstall NoobTaco and see if that does anything 
    On Monday, May 31, 2021, 09:13:27 PM EDT, Zack Gall ***@***.***> wrote:  
 
  Mike, here is the list of addons I am using all together on top of ElvUI/NoobTaco
AtlasLootClassic
Attune
AuctionatorBagonDecursiveDejamarkDismounterDominosGatherMate2ItemRackLeatrix MapsMik's SBTPawnPortal MageRCLootCouncilRecountThreatClassicWeakaurasCharacterStatsTBCDBM
Any of these you think could cause that issue with the lvl not showing for 60? I will try turning off each addon 1 at a time to see which one it could be. 
    On Monday, May 31, 2021, 02:50:04 PM EDT, Zack Gall ***@***.***> wrote:  
 
 Super weird. I don’t think I have any other addons that affect it. Most notable ones are 
AttuneDBMPAWNGatherMate2BaggonAuctioner
I will send the full list when I get back to my PC, but it used to work perfectly up until an update of some sort. 
Sent from my iPhone

On May 31, 2021, at 12:42 PM, Mike Norton ***@***.***> wrote:



﻿


Hello @xmcdizzle This could be from another addon or screen res. I will keep looking into being able to replicate but so far, I do not see the same issue.

Can you give me more information about other addons you might be running that could be conflicting?

Thanks

**Comment by xmcdizzle** [comment]
FIXED the problem. It had to do with which font was selected. For whatever reason, 60 in a certain font, maybe it was just a fraction of a hair size too large, showed "..." rather than lvl 60. 
    On Monday, May 31, 2021, 09:15:15 PM EDT, Zack Gall ***@***.***> wrote:  
 
  So the first Addon I disabled just to see, was NoobTacoUI. The level 60 now shows. I am going to reinstall NoobTaco and see if that does anything 
    On Monday, May 31, 2021, 09:13:27 PM EDT, Zack Gall ***@***.***> wrote:  
 
  Mike, here is the list of addons I am using all together on top of ElvUI/NoobTaco
AtlasLootClassic
Attune
AuctionatorBagonDecursiveDejamarkDismounterDominosGatherMate2ItemRackLeatrix MapsMik's SBTPawnPortal MageRCLootCouncilRecountThreatClassicWeakaurasCharacterStatsTBCDBM
Any of these you think could cause that issue with the lvl not showing for 60? I will try turning off each addon 1 at a time to see which one it could be. 
    On Monday, May 31, 2021, 02:50:04 PM EDT, Zack Gall ***@***.***> wrote:  
 
 Super weird. I don’t think I have any other addons that affect it. Most notable ones are 
AttuneDBMPAWNGatherMate2BaggonAuctioner
I will send the full list when I get back to my PC, but it used to work perfectly up until an update of some sort. 
Sent from my iPhone

On May 31, 2021, at 12:42 PM, Mike Norton ***@***.***> wrote:



﻿


Hello @xmcdizzle This could be from another addon or screen res. I will keep looking into being able to replicate but so far, I do not see the same issue.

Can you give me more information about other addons you might be running that could be conflicting?

Thanks

**Comment by NoobTaco** [comment]
> FIXED the problem. It had to do with which font was selected. For whatever reason, 60 in a certain font, maybe it was just a fraction of a hair size too large, showed "..." rather than lvl 60.

Oh! Nice. I was about to suggest disabling my profile.

That is a good find, however. What language client are you using by chance? I had only tested for US and wonder if Montserrat font was causing the issue.

I will close this issue for now, but feel free to add more to the comments.

Glad you got it worked out.

**Comment by xmcdizzle** [comment]
> > FIXED the problem. It had to do with which font was selected. For whatever reason, 60 in a certain font, maybe it was just a fraction of a hair size too large, showed "..." rather than lvl 60.
> 
> Oh! Nice. I was about to suggest disabling my profile.
> 
> That is a good find, however. What language client are you using by chance? I had only tested for US and wonder if Montserrat font was causing the issue.
> 
> I will close this issue for now, but feel free to add more to the comments.
> 
> Glad you got it worked out.

Totally forgot to respond to you, I’m using the US English
