### ISSUE TITLE
1.3.6 update

### ISSUE THREAD

**Issue by xmcdizzle** [NoobTaco/NoobTacoUI#30]
Hello, 

I have your UI pack installed, and have gone through the steps of updating it and going through the setup process. However, even after updating the UI, every single time I reload UI, relog, etc. the setup always comes back and wants me to do it again. 

I have tried creating a new profile, updating current, and both of them do the same thing.

**Comment by NoobTaco** [comment]
Hi @xmcdizzle that is strange behavior. I will double check and see if something got missed in that update.

**Comment by NoobTaco** [comment]
Could you provide some information for me?

- What version of wow are you playing? Retail, Classic, TBC ect
- What version of ElvUI are you using?
- Do you by chance have special characters in your name?

Let's start there and see what I can find. If this fails to result anything then I would like to look at your ElvUI.wtf file to see if the profile is correctly adding the right entry for the version update.

Thanks

**Comment by xmcdizzle** [comment]
This occurred during TBC -> it is now prepatch into wrath
ElvUI 3.0
No special characters in name

**Comment by NoobTaco** [comment]
Is it still happening to you?

I can't replicate on my end.

**Comment by xmcdizzle** [comment]
It is not happening anymore. I have been able to skip process and it not show anymore. Not entirely what sure was causing it, maybe something on ElvUI side or maybe even WoW.
