### ISSUE TITLE
Overlap with new Ghoul bar tracking placement

### ISSUE THREAD

**Issue by boktai1000** [NoobTaco/NoobTacoUI#35]
In the latest ElvUI, they added support so that Death Knights can see their Ghoul's time remaining as well as dismiss the pet via right click (Non-Unholy DKs Ghouls are not treated as pets, they act more as Totem 1).

See screenshot here, there is just some slight overlap of it's placement in a default configuration. Screenshot taken from PTR where a clean install was easy to perform and showcase with no other addons.

![image](https://user-images.githubusercontent.com/9054563/191154309-e8643c7f-f120-490e-b85c-64da63bf245d.png)

**Comment by boktai1000** [comment]
Here's a better screenshot of it, it's visible in the bottom left of the screen slightly overlapping part of the actionbar.

![image](https://user-images.githubusercontent.com/9054563/191154537-bb5b85e1-afdd-4592-b4e1-50ed5fe8dac4.png)

**Comment by NoobTaco** [comment]
Yes, let me take a look. I missed this addition update it would seem.
