### ISSUE TITLE
Wago analytics broke the addon

### ISSUE THREAD

**Issue by martinnyborg** [NoobTaco/NoobTacoUI#60]
My friend and I get error messages from the NoobTacoUI with the latest 1.5.3 version, downgrading to 1.5.2 fixes it. 

The error: Interface/AddOns/NoobTacoUI/core/Code.lua:2: Cannot find a library instance of "WagoAnalytics".

![image](https://github.com/user-attachments/assets/4d3c8439-8888-44a4-81dd-801913a88fa0)

**Comment by andreash-dev** [comment]
I had the same issue. Downgraded to version 1.5.2, and it works like a charm now.
Hopefully, it gets fixed soon.
